import { Inter } from 'next/font/google'
import './globals.css'
import Theme from "@/components/Theme";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Theme>
          <header></header>
          <div>
            <nav></nav>
            <main>{children}</main>
          </div>
        </Theme>
      </body>
    </html>
  )
}
